"""`fleet mcp` — AI-agent integration for a fleet.

`config` GENERATES the consumer repo's `.mcp.json` from the fleet's own
declared settings instead of anyone hand-writing endpoint wrappers:

  * `nixos`   — generic nixpkgs/NixOS options lookup (always emitted;
                useful to any agent touching Nix code).
  * `grafana` — emitted when `fleet.settings.observability.grafanaDomain`
                is set. A small wrapper script is generated under
                .cache/fleet/mcp/ that decrypts the service-account token
                from the SOPS store at run time (nothing secret lands in
                .mcp.json or the git tree) and execs mcp-grafana via
                `nix shell` (flake-clean; no channel deps).
  * `tempo`   — emitted when `fleet.settings.observability.tempoUrl` is
                set (Tempo ships a native MCP endpoint at /api/mcp).

Settings come from the consumer flake's `settings-json` package (part of
mkFleet's output), keeping this module eval-free at steady state: one
`nix build` per invocation, no Nix evals inside the CLI itself.

Merge behavior: entries this generator owns (nixos/grafana/tempo) are
written/updated; every other entry in an existing .mcp.json is preserved
verbatim — consumer-specific servers are never touched.
"""
from __future__ import annotations

import json
import os
import stat
import subprocess
import sys
from pathlib import Path

import click
from rich.console import Console

console = Console()

OWNED_KEYS = ("nixos", "grafana", "tempo")

# SOPS path convention for the Grafana MCP service-account token
# (Viewer-role). Override with fleet.settings.mcp.grafanaTokenSopsPath.
DEFAULT_GRAFANA_TOKEN_PATH = '["services"]["grafana"]["mcp_token"]'


def _load_settings(root: Path) -> dict:
    """Build the consumer flake's settings-json package and parse it."""
    rc = subprocess.run(
        ["nix", "build", ".#settings-json", "--no-link", "--print-out-paths"],
        cwd=root, capture_output=True, text=True)
    if rc.returncode != 0:
        console.print(
            "[red]ERROR:[/red] could not build .#settings-json from this repo's "
            "flake. Your flake must re-export mkFleet's packages (fleetkit ships "
            "settings-json as part of mkFleet output).")
        console.print(rc.stderr.strip()[-500:])
        sys.exit(1)
    return json.loads(Path(rc.stdout.strip()).read_text())


def _grafana_wrapper(root: Path, grafana_url: str, token_sops_path: str,
                     secrets_file: str) -> Path:
    """Write the credential-fetching grafana wrapper; return its path."""
    d = root / ".cache" / "fleet" / "mcp"
    d.mkdir(parents=True, exist_ok=True)
    script = d / "grafana.sh"
    script.write_text(f"""#!/usr/bin/env bash
# Generated by `fleet mcp config` — do not edit (regenerate instead).
# Decrypts the Grafana MCP service-account token at launch; the token
# never lands in .mcp.json or the git tree.
set -euo pipefail
TOKEN="$(sops -d --extract '{token_sops_path}' '{secrets_file}')"
export GRAFANA_URL='{grafana_url}'
export GRAFANA_API_KEY="$TOKEN"
exec nix shell nixpkgs#mcp-grafana --command mcp-grafana "$@"
""")
    script.chmod(script.stat().st_mode | stat.S_IEXEC)
    return script


@click.group("mcp")
def mcp():
    """AI-agent (MCP) integration for this fleet."""


@mcp.command("config")
@click.option("--stdout", "to_stdout", is_flag=True,
              help="Print the generated .mcp.json instead of writing it.")
def mcp_config(to_stdout: bool):
    """Generate .mcp.json from the fleet's declared settings.

    Derives MCP server entries from fleet.settings (via the flake's
    settings-json package) — endpoints and credentials are never
    hand-written. Preserves any entries in an existing .mcp.json that
    this generator does not own.
    """
    from ._util import find_project_root
    from .config import secrets_file as _cfg_secrets, get as _cfg_get

    root = Path(find_project_root())
    settings = _load_settings(root)
    obs = settings.get("observability") or {}

    servers: dict = {}

    servers["nixos"] = {
        "type": "stdio",
        "command": "nix",
        "args": ["run", "github:utensils/mcp-nixos", "--"],
    }

    grafana_domain = obs.get("grafanaDomain")
    if grafana_domain:
        url = grafana_domain if "://" in grafana_domain else f"http://{grafana_domain}"
        token_path = _cfg_get("mcp.grafana_token_sops_path",
                              DEFAULT_GRAFANA_TOKEN_PATH)
        wrapper = _grafana_wrapper(root, url, token_path, str(_cfg_secrets()))
        servers["grafana"] = {
            "type": "stdio",
            "command": str(wrapper),
            "args": [],
        }

    tempo_url = obs.get("tempoUrl")
    if tempo_url:
        servers["tempo"] = {
            "type": "http",
            "url": tempo_url.rstrip("/") + "/api/mcp",
        }

    mcp_file = root / ".mcp.json"
    existing: dict = {}
    if mcp_file.exists():
        try:
            existing = json.loads(mcp_file.read_text())
        except json.JSONDecodeError:
            console.print(f"[red]ERROR:[/red] {mcp_file} is not valid JSON — fix or remove it first.")
            sys.exit(1)
    merged = dict(existing)
    merged.setdefault("mcpServers", {})
    preserved = {k: v for k, v in merged["mcpServers"].items() if k not in OWNED_KEYS}
    merged["mcpServers"] = {**preserved, **servers}

    out = json.dumps(merged, indent=2) + "\n"
    if to_stdout:
        click.echo(out)
        return
    mcp_file.write_text(out)
    kept = ", ".join(sorted(preserved)) or "none"
    console.print(f"[green]wrote[/green] {mcp_file}  "
                  f"(generated: {', '.join(sorted(servers))}; preserved: {kept})")
